# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9458921a4b56e58e8b626de005018e819dd875d51bc8496e28c0883d1466993dc4f08f45bbe7f6d4a7e78b65f360106393fef71e8145f4f317115a3ecec2b3a2

test:
  secret_key_base: 13c1cbc11b5b96e65bd328414c0719254fd28a8900ccde763a74fe947bdfc74ea19398eebecfef41145afd784af9b874a19b445495ef1ad972fabb17effae95c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
